apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-adeleke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-adeleke
  template:
    metadata:
      labels:
        app: redis-adeleke
    spec:
      containers:
      - name: redis-adeleke
        image:  redis
        ports:
        - containerPort: 6379
